module.exports = {
  apps: [
    {
      name: "api",
      script: "./servers/api-server.js",
      instances: "1",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "development",
        PORT: 3000,
        LOG_LEVEL: "info",
        DB_HOST: "localhost",
        DB_USER: "root",
        DB_PASS: "password",
        DB_NAME: "db_notes",
        TOKEN_SECRET: "dev_jwt_secret_key",
        REFRESH_TOKEN_SECRET: "dev_refresh_token_secret_key",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3001,
        LOG_LEVEL: "debug",
        DB_HOST: "localhost",
        DB_USER: "root",
        DB_PASS: "password",
        DB_NAME: "db_notes",
        TOKEN_SECRET: "prod_jwt_secret_key",
        REFRESH_TOKEN_SECRET: "prod_refresh_token_secret_key",
      },
      env_staging: {
        NODE_ENV: "staging",
        PORT: 3002,
        LOG_LEVEL: "warn",
        DB_HOST: "localhost",
        DB_USER: "root",
        DB_PASS: "password",
        DB_NAME: "db_notes",
        TOKEN_SECRET: "staging_jwt_secret_key",
        REFRESH_TOKEN_SECRET: "staging_refresh_token_secret_key",
      },
      watch: false,
      max_memory_restart: "512M",
      log_file: "./logs/api/pm2.log",
      out_file: "./logs/api/out.log",
      error_file: "./logs/api/error.log",
      time: true,
    },
    {
      name: "socket",
      script: "./servers/socket-server.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "development",
        SOCKET_PORT: 4000,
        LOG_LEVEL: "debug",
      },
      env_production: {
        NODE_ENV: "production",
        SOCKET_PORT: 4001,
        LOG_LEVEL: "info",
      },
      env_staging: {
        NODE_ENV: "staging",
        SOCKET_PORT: 4002,
        LOG_LEVEL: "warn",
      },
      watch: false,
      max_memory_restart: "256M",
      log_file: "./logs/socket/pm2.log",
      out_file: "./logs/socket/out.log",
      error_file: "./logs/socket/error.log",
      time: true,
    },
  ],
};
